### ISSUE TITLE
No authentication failure for the wrong credentials 

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/test-pages#13]
Description: No authentication failure for entering wrong user name and password in the turn server credentials 

Steps:

Go to https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
Remove the Stun server by Clicking and pressing "Remove server" button
Enter the Valid Turn server URI (Ex: turn:134.136.11.66:3478 in the URI Field, Wrong username "1454369900:121055630" and wrong password "E6IhmNYudfhdxios5LmwAKEif7Cf0g0="

Expected :  "Authentication failed?" message should appear in the Candidates section
Actual : No message that the authentication failed.

**Comment by KaptenJansson** [comment]
This is by design I believe, stun and turn servers are silent in that case to prevent abuse.
