### ISSUE TITLE
Fix the Menifest file in the test page for Screensharing Extension

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/test-pages#17]
Problem: Desktop Screencapture is not working.

Expected Result: 
"content_scripts":  and "permissions": have wrong links, the correct link would be https://webrtc.github.io/test-pages/src/peer2peer/* so that the desktop screen capture will work.

**Comment by KaptenJansson** [comment]
FYI you can add "Fixes #issuenumber" in the PR to auto close bugs when the PR is merged.
